use vulkano::{ //Used as  GPU API
    library::VulkanLibrary,  
    instance::{Instance, InstanceCreateInfo}, //vulkan driver 
    device::{ 
        physical::PhysicalDevice, //gpu hardware
        Device, DeviceCreateInfo, DeviceExtensions, Features, Queue, QueueCreateInfo, QueueFlags},   //gpu virtual machine  
    format::Format, //Pixel format
    buffer::{Buffer, BufferContents, BufferCreateInfo, BufferUsage, Subbuffer}, //data stored in Vram
    image::{ //multidimensional buffer
        view::ImageView, Image, ImageUsage}, 
    memory::allocator::{AllocationCreateInfo, MemoryAllocator, MemoryTypeFilter, StandardMemoryAllocator}, //how to allocate objects in vram
    command_buffer::{ //Lists of commands sent to GPU from CPU
        allocator::{
            StandardCommandBufferAllocator, StandardCommandBufferAllocatorCreateInfo}, 
        AutoCommandBufferBuilder, CommandBufferExecFuture, CommandBufferUsage, PrimaryAutoCommandBuffer, RenderPassBeginInfo, SubpassBeginInfo, SubpassContents}, 
        swapchain::{self, PresentFuture, PresentMode, Surface, Swapchain, SwapchainAcquireFuture, SwapchainCreateInfo, SwapchainPresentInfo}, 
    render_pass::{Framebuffer, FramebufferCreateInfo, RenderPass, Subpass}, //function signatures for custom GPU actions
    shader::{ShaderModule, ShaderStages}, //code that runs on the GPU
    pipeline::{ //a rendering operation
        graphics::{
            color_blend::{ColorBlendAttachmentState, ColorBlendState}, 
            input_assembly::InputAssemblyState, 
            multisample::MultisampleState, 
            rasterization::{CullMode, PolygonMode, RasterizationState}, 
            vertex_input::{Vertex, VertexDefinition}, 
            viewport::{Viewport, ViewportState}, 
            GraphicsPipelineCreateInfo}, 
        layout::{PipelineDescriptorSetLayoutCreateInfo, PushConstantRange}, //data the rendering operation needs
        GraphicsPipeline, PipelineLayout, PipelineShaderStageCreateInfo}, 
    sync::{self, //synchronize the CPU and the GPU
        future::{FenceSignalFuture, JoinFuture, NowFuture}, 
        GpuFuture}, 
Validated, VulkanError 
};
use winit::{ //Used for cross-platform window creation
    application::ApplicationHandler, 
    dpi::LogicalSize, 
    event::WindowEvent, 
    event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy}, 
    window::{Window, WindowAttributes}};
use std::{str::FromStr, sync::{Arc, RwLock}, thread::{self, sleep, JoinHandle}, time::Duration};

//a vertex shader module generated by a crazy macro
//contains functions for compiling it on a gpu virtual machine
//executes for each vertex in a draw command
mod vs { 
    vulkano_shaders::shader! {
        ty: "vertex",
        src: r"
            #version 460

            layout(location = 0) in vec2 position;
            layout(location = 1) in vec2 uv;
            layout(location = 0) out vec2 fragCoord;

            void main() {
                fragCoord = uv;
                gl_Position = vec4(position, 0.0, 1.0);
            }
        ",
    }
}

//same as vs, but a fragment shader
//executes for each pixel in a draw command
mod fs { 
    vulkano_shaders::shader! {
        ty: "fragment",
        src: r"
            #version 460

            layout(location = 0) out vec4 fragColor;
            layout(location = 0) in vec2 fragCoord;
            layout( push_constant ) uniform constants 
            {
                float iTime;
                vec3 iResolution;
            } pc;

            float sun(vec2 uv, float battery)
{
 	float val = smoothstep(0.3, 0.29, length(uv));
 	float bloom = smoothstep(0.7, 0.0, length(uv));
    float cut = 3.0 * sin((uv.y + pc.iTime * 0.2 * (battery + 0.02)) * 100.0) 
				+ clamp(uv.y * 14.0 + 1.0, -6.0, 6.0);
    cut = clamp(cut, 0.0, 1.0);
    return clamp(val * cut, 0.0, 1.0) + bloom * 0.6;
}

float grid(vec2 uv, float battery)
{
    vec2 size = vec2(uv.y, uv.y * uv.y * 0.2) * 0.01;
    uv += vec2(0.0, pc.iTime * 4.0 * (battery + 0.05));
    uv = abs(fract(uv) - 0.5);
 	vec2 lines = smoothstep(size, vec2(0.0), uv);
 	lines += smoothstep(size * 5.0, vec2(0.0), uv) * 0.4 * battery;
    return clamp(lines.x + lines.y, 0.0, 3.0);
}

float dot2(in vec2 v ) { return dot(v,v); }

float sdTrapezoid( in vec2 p, in float r1, float r2, float he )
{
    vec2 k1 = vec2(r2,he);
    vec2 k2 = vec2(r2-r1,2.0*he);
    p.x = abs(p.x);
    vec2 ca = vec2(p.x-min(p.x,(p.y<0.0)?r1:r2), abs(p.y)-he);
    vec2 cb = p - k1 + k2*clamp( dot(k1-p,k2)/dot2(k2), 0.0, 1.0 );
    float s = (cb.x<0.0 && ca.y<0.0) ? -1.0 : 1.0;
    return s*sqrt( min(dot2(ca),dot2(cb)) );
}

float sdLine( in vec2 p, in vec2 a, in vec2 b )
{
    vec2 pa = p-a, ba = b-a;
    float h = clamp( dot(pa,ba)/dot(ba,ba), 0.0, 1.0 );
    return length( pa - ba*h );
}

float sdBox( in vec2 p, in vec2 b )
{
    vec2 d = abs(p)-b;
    return length(max(d,vec2(0))) + min(max(d.x,d.y),0.0);
}

float opSmoothUnion(float d1, float d2, float k){
	float h = clamp(0.5 + 0.5 * (d2 - d1) /k,0.0,1.0);
    return mix(d2, d1 , h) - k * h * ( 1.0 - h);
}

float sdCloud(in vec2 p, in vec2 a1, in vec2 b1, in vec2 a2, in vec2 b2, float w)
{
	//float lineVal1 = smoothstep(w - 0.0001, w, sdLine(p, a1, b1));
    float lineVal1 = sdLine(p, a1, b1);
    float lineVal2 = sdLine(p, a2, b2);
    vec2 ww = vec2(w*1.5, 0.0);
    vec2 left = max(a1 + ww, a2 + ww);
    vec2 right = min(b1 - ww, b2 - ww);
    vec2 boxCenter = (left + right) * 0.5;
    //float boxW = right.x - left.x;
    float boxH = abs(a2.y - a1.y) * 0.5;
    //float boxVal = sdBox(p - boxCenter, vec2(boxW, boxH)) + w;
    float boxVal = sdBox(p - boxCenter, vec2(0.04, boxH)) + w;
    
    float uniVal1 = opSmoothUnion(lineVal1, boxVal, 0.05);
    float uniVal2 = opSmoothUnion(lineVal2, boxVal, 0.05);
    
    return min(uniVal1, uniVal2);
}

void main()
{
    vec2 uv = (2.0 * fragCoord.xy - pc.iResolution.xy)/pc.iResolution.y;
    float battery = 1.0;
    //if (iMouse.x > 1.0 && iMouse.y > 1.0) battery = iMouse.y / pc.iResolution.y;
    //else battery = 0.8;
    
    //if (abs(uv.x) < (9.0 / 16.0))
    {
        // Grid
        float fog = smoothstep(0.1, -0.02, abs(uv.y + 0.2));
        vec3 col = vec3(0.0, 0.1, 0.2);
        if (uv.y < -0.2)
        {
            uv.y = 3.0 / (abs(uv.y + 0.2) + 0.05);
            uv.x *= uv.y * 1.0;
            float gridVal = grid(uv, battery);
            col = mix(col, vec3(1.0, 0.5, 1.0), gridVal);
        }
        else
        {
            float fujiD = min(uv.y * 4.5 - 0.5, 1.0);
            uv.y -= battery * 1.1 - 0.51;
            
            vec2 sunUV = uv;
            vec2 fujiUV = uv;
            
            // Sun
            sunUV += vec2(0.75, 0.2);
            //uv.y -= 1.1 - 0.51;
            col = vec3(1.0, 0.2, 1.0);
            float sunVal = sun(sunUV, battery);
            
            col = mix(col, vec3(1.0, 0.4, 0.1), sunUV.y * 2.0 + 0.2);
            col = mix(vec3(0.0, 0.0, 0.0), col, sunVal);
            
            // fuji
            float fujiVal = sdTrapezoid( uv  + vec2(-0.75+sunUV.y * 0.0, 0.5), 1.75 + pow(uv.y * uv.y, 2.1), 0.2, 0.5);
            float waveVal = uv.y + sin(uv.x * 20.0 + pc.iTime * 2.0) * 0.05 + 0.2;
            float wave_width = smoothstep(0.0,0.01,(waveVal));
            
            // fuji color
            col = mix( col, mix(vec3(0.0, 0.0, 0.25), vec3(1.0, 0.0, 0.5), fujiD), step(fujiVal, 0.0));
            // fuji top snow
            col = mix( col, vec3(1.0, 0.5, 1.0), wave_width * step(fujiVal, 0.0));
            // fuji outline
            col = mix( col, vec3(1.0, 0.5, 1.0), 1.0-smoothstep(0.0,0.01,abs(fujiVal)) );
            //col = mix( col, vec3(1.0, 1.0, 1.0), 1.0-smoothstep(0.03,0.04,abs(fujiVal)) );
            //col = vec3(1.0, 1.0, 1.0) *(1.0-smoothstep(0.03,0.04,abs(fujiVal)));
            
            // horizon color
            col += mix( col, mix(vec3(1.0, 0.12, 0.8), vec3(0.0, 0.0, 0.2), clamp(uv.y * 3.5 + 3.0, 0.0, 1.0)), step(0.0, fujiVal) );
            
            // cloud
            vec2 cloudUV = uv;
            cloudUV.x = mod(cloudUV.x + pc.iTime * 0.1, 4.0) - 2.0;
            float cloudTime = pc.iTime * 0.5;
            float cloudY = -0.5;
            float cloudVal1 = sdCloud(cloudUV, 
                                     vec2(0.1 + sin(cloudTime + 140.5)*0.1,cloudY), 
                                     vec2(1.05 + cos(cloudTime * 0.9 - 36.56) * 0.1, cloudY), 
                                     vec2(0.2 + cos(cloudTime * 0.867 + 387.165) * 0.1,0.25+cloudY), 
                                     vec2(0.5 + cos(cloudTime * 0.9675 - 15.162) * 0.09, 0.25+cloudY), 0.075);
            cloudY = -0.6;
            float cloudVal2 = sdCloud(cloudUV, 
                                     vec2(-0.9 + cos(cloudTime * 1.02 + 541.75) * 0.1,cloudY), 
                                     vec2(-0.5 + sin(cloudTime * 0.9 - 316.56) * 0.1, cloudY), 
                                     vec2(-1.5 + cos(cloudTime * 0.867 + 37.165) * 0.1,0.25+cloudY), 
                                     vec2(-0.6 + sin(cloudTime * 0.9675 + 665.162) * 0.09, 0.25+cloudY), 0.075);
            
            float cloudVal = min(cloudVal1, cloudVal2);
            
            //col = mix(col, vec3(1.0,1.0,0.0), smoothstep(0.0751, 0.075, cloudVal));
            col = mix(col, vec3(0.0, 0.0, 0.2), 1.0 - smoothstep(0.075 - 0.0001, 0.075, cloudVal));
            col += vec3(1.0, 1.0, 1.0)*(1.0 - smoothstep(0.0,0.01,abs(cloudVal - 0.075)));
        }

        col += fog * fog * fog;
        col = mix(vec3(col.r, col.r, col.r) * 0.5, col, battery * 0.7);

        fragColor = vec4(col,1.0);
    }
    //else fragColor = vec4(0.0);

    
}
        ",
    }
}

static WINDOW_INIT_WIDTH : u32 = 600;
static WINDOW_INIT_HEIGHT : u32 = 400;

fn main() {
    
    let event_loop: EventLoop<UserEvent> = EventLoop::<UserEvent>::with_user_event().build().unwrap();
    //proxy loop used to send custom UserEvents
    //allows multiple threads to interact with the application
    let proxy_loop: winit::event_loop::EventLoopProxy<UserEvent> = event_loop.create_proxy();

    let vulkan_driver = initialize_vulkano(&event_loop);

    //The application stores all the data the application needs to run, 
    //most of them are optional, set to None since we can't initialize them until the window is made
    let mut render_app: Application = Application {
        vk_driver: vulkan_driver,
        event_loop_proxy: Some(Arc::new(RwLock::new(proxy_loop))),
        window_create_info: Window::default_attributes() //data window initially starts out with
            .with_blur(false)
            .with_inner_size(LogicalSize::new(WINDOW_INIT_WIDTH, WINDOW_INIT_HEIGHT))
            .with_resizable(true)
            .with_title(String::from_str("Test Renderer").unwrap())
            .with_maximized(false)
            .with_visible(true)
            .with_transparent(false),
        ..Default::default()
    };
    //This will internally call the impl application handler resumed() function and start the application
    event_loop.run_app(&mut render_app).unwrap();
    //all application behavior is done through the applicationHandler trait
}

#[derive(Debug, Clone, Copy)]
enum UserEvent { //custom event sent to application from another thread
    Render
}

#[derive(BufferContents, Vertex)]
#[repr(C)]
struct Vert { //a custom vertex that will be stored in Vram and immutably read by the vertex shaders
    #[format(R32G32_SFLOAT)]
    position: [f32; 2],

    #[format(R32G32_SFLOAT)]
    uv: [f32; 2]
}

struct Application {
    vk_driver : Arc<Instance>,
    vk_gpu : Option<(Arc<PhysicalDevice>, Vec<u32>)>,
    vk_virtual_gpu : Option<(Arc<Device>, Vec<Arc<Queue>>)>,

    swapchain_invalid : bool, //window resizing requires us to recreate the swapchain
    window_create_info : WindowAttributes, //initial window creation data
    window_main : Option<(Arc<Window>, Arc<Surface>)>, //surface is the rendering context for the window

    //swapchain is the method for flipping images to the surface from the gpu
    //when making one we also get a vector of images to draw to, the swapchain images
    swapchain : Option<(Arc<Swapchain>, Vec<Arc<Image>>)>, 

    memory_allocator : Option<Arc<dyn MemoryAllocator>>,
    command_allocator : Option<StandardCommandBufferAllocator>,
    vert_buffer : Option<Subbuffer<[Vert]>>, //the vertex buffer that is rendered
    render_pass : Option<Arc<RenderPass>>,
    //the output image of a draw call, we need three for each swapchain image
    //on the hardware, these are the same as the swapchain images
    render_buffers : Option<Vec<Arc<Framebuffer>>>, 
    
    vert_shader : Option<Arc<ShaderModule>>, //compiled shaders
    frag_shader : Option<Arc<ShaderModule>>,

    render_pipeline : Option<Arc<GraphicsPipeline>>, //the render command
    render_pipeline_layout : Option<Arc<PipelineLayout>>, //we need to also save the render command's function signature

    command_buffers : Option<Vec<Arc<PrimaryAutoCommandBuffer>>>, //the full list of commands to send the gpu
    current_time : f32,
    render_notify_thread : Option<JoinHandle<()>>, //a different thread that issues the draw commands to the application
    //a data type that is transferable between threads, that is used to block a thread until the gpu is completed with a command
    render_fence : Arc<RwLock<Option<Arc<FenceSignalFuture<PresentFuture<CommandBufferExecFuture<JoinFuture<NowFuture, SwapchainAcquireFuture>>>>>>>>,
    continue_render : Arc<RwLock<bool>>, //bool for controlling the render_notify_thread
    event_loop_proxy : Option<Arc<RwLock<EventLoopProxy<UserEvent>>>>, //a proxy loop allows one to send custom events to the application, in this case it is also cross-thread

}

//default application, mostly set to None values. Used with struct update syntax in main()
impl Default for Application {
    fn default() -> Self {
        Self { 
            vk_driver: {vulkano::instance::Instance::new(vulkano::VulkanLibrary::new().unwrap(), InstanceCreateInfo::default()).unwrap()}, 
            vk_gpu: None,
            vk_virtual_gpu: None, 
            event_loop_proxy: None,
            window_create_info: WindowAttributes::default(), 
            window_main: None, 
            swapchain: None, 
            memory_allocator: None, 
            command_allocator: None, 
            vert_buffer: None, 
            render_pass: None, 
            render_buffers: None, 
            vert_shader: None, 
            frag_shader: None, 
            render_pipeline: None,
            command_buffers: None,
            swapchain_invalid: false,
            current_time: 0.0,
            render_notify_thread : None,
            render_fence : Arc::new(RwLock::new(None)),
            continue_render : Arc::new(RwLock::new(true)),
            render_pipeline_layout : None
        }
    }
}

//various useful functions for my application
impl Application {
    fn build_window(&mut self, event_loop : &ActiveEventLoop) {
        let new_window = Arc::new(event_loop.create_window(self.window_create_info.clone())
        .unwrap());

        //https://docs.rs/vulkano/latest/vulkano/swapchain/struct.Surface.html
        //Says that making a surface is platform specific, so we might need to do conditional compilation for certain platforms
        let window_surface = Surface::from_window(self.vk_driver.clone(), new_window.clone())
                .unwrap();

        self.window_main = Some((new_window, window_surface))
    }

    fn initialize_gpu(&mut self) {
        //gets a valid physical gpu
        let device_extensions = DeviceExtensions{
            khr_swapchain: true,
            ..Default::default()
        };
        let surface = self.window_main.as_ref().unwrap().1.clone();

        let device = locate_device(self.vk_driver.clone(), &device_extensions, surface).unwrap();
        self.vk_gpu = Some(device);
    }

    fn initialize_virtual_gpu(&mut self) {
        //sets up the vulkan gpu virtual machine
        let (gpu, queue_indices) = self.vk_gpu.as_ref().unwrap().clone();
        let virtual_gpu_params : DeviceCreateInfo;
        
        let vk_extensions = DeviceExtensions {
            khr_swapchain: true,
            ..Default::default()
        };

        let device_features = Features {
            ..Default::default()
        };

        let queue_params = QueueCreateInfo {
            queue_family_index: queue_indices[0],
            ..Default::default()
        };

        virtual_gpu_params = DeviceCreateInfo {
            enabled_extensions: vk_extensions,
            enabled_features: device_features,
            queue_create_infos: vec![queue_params],
            ..Default::default()
        };

        let (device, queues_iter) = Device::new(gpu, virtual_gpu_params).unwrap();

        //the queues are physical (virtual on mobile) data channels to the GPU
        let queues: Vec<Arc<Queue>> = queues_iter.collect();

        self.vk_virtual_gpu = Some((device, queues))
    }

    fn build_swapchain(&mut self) {
        //make the swapchain from the wndow surface for the first time
        let (gpu, queues) = self.vk_virtual_gpu.as_ref().unwrap();
        let (window, surface) = self.window_main.as_ref().unwrap();
        
        let capabilities = self.vk_virtual_gpu.as_ref().unwrap().0
            .physical_device()
            .surface_capabilities(surface, Default::default())
            .unwrap();
        let window_size = self.window_extend();
        let composite_alpha = capabilities.supported_composite_alpha.into_iter().next().unwrap();
        let format = self.vk_gpu.as_ref().unwrap().0
        .surface_formats(&surface, Default::default())
        .unwrap()[0]
        .0;

        let swapchain_parameters = SwapchainCreateInfo {
            min_image_count: capabilities.min_image_count + 1,
            image_format: format,
            image_extent: window_size,
            image_usage: ImageUsage::COLOR_ATTACHMENT,
            composite_alpha: composite_alpha,
            present_mode : PresentMode::Mailbox,
            ..Default::default()
        };

        let (swapchain, swapchain_images) = Swapchain::new(gpu.clone(), surface.clone(), swapchain_parameters).unwrap();
        self.swapchain = Some((swapchain, swapchain_images));
    }

    fn build_renderpass(&mut self) {
        let render_pass : Arc<RenderPass> = vulkano::single_pass_renderpass!(
            self.vk_virtual_gpu.as_ref().unwrap().0.clone(),
            attachments: {
                color: {
                    format: self.render_format_or(Format::R8G8B8A8_UNORM),
                    samples: 1,
                    load_op: Clear,
                    store_op: Store
                },
            },
            pass: {
                color: [color],
                depth_stencil: {},
            },
        ).unwrap();

        self.render_pass = Some(render_pass);
    }

    fn build_framebuffers(&mut self) {
        assert!(self.swapchain.is_some());
        assert!(self.render_pass.is_some());

        let render_pass: Arc<RenderPass> = self.render_pass.as_ref().unwrap().clone();
        let swapchain: (Arc<Swapchain>, Vec<Arc<Image>>) = self.swapchain.as_ref().unwrap().clone();
        let window_size = self.window_main.as_ref().unwrap().0.inner_size();

        let render_buffers : Vec<Arc<Framebuffer>> = swapchain.1.into_iter().map(|img| {
            let img_format = img.format();
            let img_view = ImageView::new_default(img.clone())
            .unwrap();

            Framebuffer::new(
                render_pass.clone(),
                FramebufferCreateInfo {
                    attachments: vec![img_view],
                    ..Default::default()
                }
            ).unwrap()
        }).collect::<Vec<_>>();

        self.render_buffers = Some(render_buffers);
    }

    fn compile_shaders(&mut self) {
        let gpu = self.vk_virtual_gpu.as_ref().unwrap().0.clone();
        self.vert_shader = Some(vs::load(gpu.clone()).unwrap());
        self.frag_shader = Some(fs::load(gpu.clone()).unwrap());
    }

    fn build_pipeline(&mut self) {
        let window_size = self.window_main.as_ref().unwrap().0.inner_size();

        let viewport = Viewport {
            offset: [0.0, 0.0],
            extent: [window_size.width as f32, window_size.height as f32],
            depth_range: 0.0..=1.0, //<-- since the format is UNORM I think
        };
        
        let vs = self.vert_shader.as_ref().unwrap().clone().entry_point("main").unwrap();
        let fs = self.frag_shader.as_ref().unwrap().clone().entry_point("main").unwrap();

        let vert_input = Vert::per_vertex()
            .definition(&vs.info().input_interface)
            .unwrap();

        let push_constants = PushConstantRange { //custom data type I made that gets sent to GPU, used for TIME
            offset: 0,
            size: 28,
            stages: ShaderStages::FRAGMENT
        };

        let push = fs::constants{
        iTime: 0.0.into(),
        iResolution: [1.0, 1.0, 1.0]
        };

        let stages = [ //function signatures of each shader stage
            PipelineShaderStageCreateInfo::new(vs),
            PipelineShaderStageCreateInfo::new(fs)
        ];

        let vk_device = self.vk_virtual_gpu.as_ref().unwrap().0.clone();

        let layout_create_info = PipelineDescriptorSetLayoutCreateInfo::from_stages(&stages);

        //function signature of entire pipeline
        let layout = PipelineLayout::new(
            vk_device.clone(), 
            PipelineDescriptorSetLayoutCreateInfo{
                push_constant_ranges: vec![push_constants],
                flags: layout_create_info.flags,
                set_layouts: layout_create_info.set_layouts
            }.into_pipeline_layout_create_info(vk_device.clone()).unwrap()
        ).unwrap();
        self.render_pipeline_layout = Some(layout.clone());

        let subpass = Subpass::from(self.render_pass.as_ref().unwrap().clone(), 0).unwrap();

        let rasterize_stage = RasterizationState {
            depth_clamp_enable: false,
            rasterizer_discard_enable: false,
            polygon_mode: PolygonMode::Fill,
            cull_mode: CullMode::None,
            ..Default::default()
        };

        let inputstate = InputAssemblyState{
            topology: vulkano::pipeline::graphics::input_assembly::PrimitiveTopology::TriangleStrip,
            ..Default::default()
        };

        //the graphics pipeline contains 2 programmable stages (vertex and fragment), 
        //the other stages are controlled via states in a state machine
        let graphic_pipeline = GraphicsPipeline::new(
            vk_device.clone(), 
            None, 
            GraphicsPipelineCreateInfo{
                
                stages: stages.into_iter().collect(),
                vertex_input_state: Some(vert_input), 
                input_assembly_state: Some(inputstate),
                rasterization_state: Some(rasterize_stage),
                multisample_state: Some(MultisampleState::default()),
                color_blend_state: Some(ColorBlendState::with_attachment_states(
                subpass.num_color_attachments(),
                ColorBlendAttachmentState::default(),
                )),
                subpass: Some(subpass.into()),
                viewport_state: Some(ViewportState {
                    viewports: [viewport].into_iter().collect(),
                    ..Default::default()
                }),
                ..GraphicsPipelineCreateInfo::layout(layout)
            }
        ).unwrap();

        self.render_pipeline = Some(graphic_pipeline);
    }

    fn build_command_buffers(&mut self) {
        //make a command buffer for each swapchain image
        let framebuffers = self.render_buffers.as_ref().unwrap().clone();
        let command_allocator = self.command_allocator.as_ref().unwrap().clone();
        let queue_index = self.vk_virtual_gpu.as_ref().unwrap().1.clone()[0].queue_family_index();
        let graphics_pipeline = self.render_pipeline.as_ref().unwrap().clone();
        let vert_buffer = self.vert_buffer.as_ref().unwrap().clone();
        let graphic_pipeline_layout = self.render_pipeline_layout.as_ref().unwrap().clone();
        let resolution = self.window_extend().map(|f| {f as f32 / 1000.0});

        let new_command_buffers : Vec<Arc<PrimaryAutoCommandBuffer>> = framebuffers
            .iter()
            .map(|framebuffer| { 
                let mut builder = AutoCommandBufferBuilder::primary(
                    command_allocator, 
                    queue_index, 
                    CommandBufferUsage::MultipleSubmit).unwrap();

                builder 
                    .begin_render_pass( //bind a render pass | a draw call function signature
                        RenderPassBeginInfo {
                            clear_values: vec![Some([0.0, 0.0, 1.0, 1.0].into())],
                            ..RenderPassBeginInfo::framebuffer(framebuffer.clone()) //with this framebuffer (made from a swapchain image) as the output
                        }, 
                        SubpassBeginInfo {
                            contents: SubpassContents::Inline,
                            ..Default::default()
                        }
                    ).unwrap() 
                    .bind_pipeline_graphics(graphics_pipeline.clone())//give the gpu the graphics draw command instructions
                    .unwrap()
                    .bind_vertex_buffers(0, vert_buffer.clone()) //the vertex that is input into the graphics pipeline, already in vram
                    .unwrap()
                    .push_constants(graphic_pipeline_layout.clone(), 0, fs::constants{iTime: self.current_time.into(), iResolution: [resolution[0], resolution[1], 0.0]}) //pass the new frame's time value
                    .unwrap()
                    .draw(4, 1, 0, 0) //issue the draw command
                    .unwrap()
                    .end_render_pass(Default::default()) //used for data cleanup I assume
                    .unwrap();

                    builder.build().unwrap()
            })
            .collect();

        self.command_buffers = Some(new_command_buffers);
    }

    fn rebuild_swapchain(&mut self) {
        //remakes the swapchain from the previous one with up to date window size
        //then remakes all the dependent objects
        let current_swapchain: Arc<Swapchain> = self.swapchain.as_ref().unwrap().0.clone();
        let new_swapchain: (Arc<Swapchain>, Vec<Arc<Image>>) = current_swapchain.recreate(
            SwapchainCreateInfo {
                image_extent: self.window_extend(),
                ..current_swapchain.create_info()
            }
        ).unwrap();
        self.swapchain = Some(new_swapchain);
        //rebuild dependencies
        self.build_framebuffers();
        self.build_pipeline();
        self.build_command_buffers();
        self.swapchain_invalid = false;
    }

    fn submit_drawcall(&mut self) {
        
        let swapchain: Arc<Swapchain> = self.swapchain.as_ref().unwrap().0.clone();
        let (device, queue) = self.vk_virtual_gpu.as_ref().unwrap().clone();
        let command = self.command_buffers.as_ref().unwrap().clone();

        //first acquire the image to draw on from the swapchain
        let (image_i, suboptimal, acquire_future) =
                match swapchain::acquire_next_image(swapchain.clone(), None)
                    .map_err(Validated::unwrap)
                {
                    Ok(r) => r,
                    Err(VulkanError::OutOfDate) => {
                        self.swapchain_invalid = true;
                        return;
                    }
                    Err(e) => panic!("failed to acquire next image: {e}"),
                };
        if suboptimal { self.swapchain_invalid = true; }

        //println!("rendering");
        //FUTURE SHENNANIGANS
        let execution = sync::now(device.clone())
                .join(acquire_future) //synchronize NOW with when the swapchain image is available
                .then_execute(queue[0].clone(), command[image_i as usize].clone()) //execute the command buffer
                .unwrap()
                .then_swapchain_present( //present the swapchain to the window
                    queue[0].clone(), 
                    SwapchainPresentInfo::swapchain_image_index(swapchain.clone(), image_i))
                .then_signal_fence_and_flush(); //signal to the CPU that it is all complete

        let mut thing = self.render_fence.write().unwrap();
        *thing = Some(Arc::new(execution.unwrap())); //store the execution, to be synchronized to later
        self.current_time = self.current_time + 0.01; //a very bad way of doing time, but it works for my purpose
    }

    fn window_extend(&self) -> [u32; 2] {
        //size of main window as a [u32, 2]
        let window = self.window_main.as_ref().unwrap().0.clone();
        return [window.inner_size().width, window.inner_size().height]
    }

    fn render_format_or(&mut self, fallback: Format) -> Format {
        //pixel format of the swapchain ex: 32 bit rgba for a pixel
        //since the render output image might not exist or be valid
        if self.swapchain.is_some() {
            return self.swapchain.as_ref().unwrap().0.image_format()
        } else { return fallback }
    }

}

//The trait that allows the application to hook into winit crate windowing ecosystem
impl ApplicationHandler<UserEvent> for Application {
    //called when the appplication starts (unless you are on an Apple device)
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if self.window_main.is_none() {
                //  -----Initialization work begin-----
            self.build_window(event_loop); 

            if self.vk_gpu.is_none() { self.initialize_gpu(); }
            if self.vk_virtual_gpu.is_none() { self.initialize_virtual_gpu(); }
            

            self.memory_allocator = Some(Arc::from(StandardMemoryAllocator::new_default(self.vk_virtual_gpu.as_ref().unwrap().0.clone())));
            self.command_allocator = Some(StandardCommandBufferAllocator::new(
                self.vk_virtual_gpu.as_ref().unwrap().0.clone(),
                 StandardCommandBufferAllocatorCreateInfo::default()));

            self.vert_buffer = Some(default_vertex_buffer(self.memory_allocator.as_ref().unwrap().clone()));

            self.build_swapchain();
            self.build_renderpass();
            self.build_framebuffers();
            self.compile_shaders();
            self.build_pipeline();
            self.build_command_buffers();
                //  -----Initialization work end-----
            
            //allows the other thread to interact with the application
            let proxy_loop = self.event_loop_proxy.as_ref().unwrap().clone();
            //whether to continue the thread or not
            let render_check = self.continue_render.clone();
            //allows the other thread to block until the gpu is ready for a draw call
            let fence = self.render_fence.clone();
            //the looping draw call of our other thread
            let thread_fn = move || {
                loop {
                sleep(Duration::from_millis(10));
                

                if *render_check.read().unwrap() { 
                    let render_fence = fence.read().unwrap().clone();
                    if let Some(fence) = render_fence {
                        fence.wait(None).unwrap();
                    }
                    
                    proxy_loop.write().unwrap().send_event(UserEvent::Render).unwrap();
                } else {
                    break;
                }
                }
            };

            self.render_notify_thread = Some( 
                thread::spawn(thread_fn)
            );
        }
        //this is the start of the app
    }

    //my custom Render command, put in the winit application event queue by a proxy event loop in another thread
    fn user_event(&mut self, event_loop: &ActiveEventLoop, event: UserEvent) {
        //println!("user event received");
        match event {
            UserEvent::Render => { 
                //if self.swapchain_invalid { self.rebuild_swapchain(); } 
                self.rebuild_swapchain(); //A very lazy way to update the time push constant, extremely unoptimized
                self.submit_drawcall(); 
            }
        }
    }

    //Standard window event handler
    fn window_event(
            &mut self,
            event_loop: &winit::event_loop::ActiveEventLoop,
            window_id: winit::window::WindowId,
            event: winit::event::WindowEvent,
        ) {
        match event {
            WindowEvent::CloseRequested => { 
                //stop the other thread and join it into this main thread
                *self.continue_render.write().unwrap() = false;
                self.render_notify_thread.take().unwrap().join().unwrap();
                event_loop.exit() //close the application
            }
            WindowEvent::RedrawRequested => { //called when the window changes size
                //println!("Redraw Request"); 
                self.swapchain_invalid = true; 
            }
            _ => { }
        }
        
    }
}


//Sets up connection to GPU
fn initialize_vulkano(event_loop : &EventLoop<UserEvent>) -> Arc<Instance> {
    let vk_library = VulkanLibrary::new().expect("failed to make vulkan library"); 
    
    //get gpu driver (instance)
    let vk_instance_parameters: InstanceCreateInfo = InstanceCreateInfo {
        enabled_extensions: Surface::required_extensions(&event_loop), //swapchain extensions
        ..Default::default()
    };
    let vk_driver: Arc<Instance> = Instance::new(
        vk_library.clone(),
        vk_instance_parameters)
        .expect("Failed to create vulkan instance");

    //we can't locate a device until we've made our window, so this is all we can do for now
    return vk_driver;
}

//find an optimal GPU to use and a graphics queue index to use
fn locate_device(vk_driver : Arc<Instance>, extensions : &DeviceExtensions, window_surface : Arc<Surface>) 
-> Option<(Arc<PhysicalDevice>, Vec<u32>)> {
    use vulkano::device::physical::PhysicalDeviceType::*;
    
    //get all devices
    //select one to be the logical device
    let graphics_processors : Vec<Arc<PhysicalDevice>> = vk_driver.enumerate_physical_devices()
        .unwrap()
        .collect();

    let selected_gpu: Option<(Arc<PhysicalDevice>, Vec<u32>)> = graphics_processors
        .into_iter()
        .filter(|gpu | {
            gpu.supported_extensions().contains(&extensions)
        })
        .map(|gpu| {
            let queue_indices : Vec<u32> = gpu.queue_family_properties().iter().enumerate()
                .filter(|(index, family)| {
                    family.queue_flags.contains(QueueFlags::GRAPHICS) 
                        && gpu.surface_support(*index as u32, &window_surface).unwrap_or(false)
                })
                .map(|(index, family)| {
                index as u32
            }).collect();

            (gpu, queue_indices)
        })
        .filter(|(gpu, queue_indices)| {
            queue_indices.len() > 0
        })
        .min_by_key(|(gpu, queue_indices)| {
            match gpu.properties().device_type{
                DiscreteGpu => 0, //rank types of gpus in order of best to worst and pick the best one
                IntegratedGpu => 1,
                VirtualGpu => 2,
                Cpu => 3,
                _ => 4
            }
        });

    return selected_gpu;
}

fn default_vertex_buffer(mem_allocator : Arc<dyn MemoryAllocator>) -> Subbuffer<[Vert]>{
    //this vertex buffer represents the 4 corners of the screen
    //2 triangles
    let vert1 = Vert { position: [-1.0, -1.0], uv: [0.0, 0.0] };
    let vert2 = Vert { position: [-1.0, 1.0], uv: [0.0, 1.0] };
    let vert3 = Vert { position: [1.0, -1.0] , uv: [1.0, 0.0] };
    let vert4 = Vert { position: [1.0, 1.0], uv: [1.0, 1.0] };

    return Buffer::from_iter(
        mem_allocator, 
        BufferCreateInfo {
            usage: BufferUsage::VERTEX_BUFFER,
            ..Default::default()
        }, 
        AllocationCreateInfo{
            memory_type_filter: MemoryTypeFilter::PREFER_DEVICE | MemoryTypeFilter::HOST_SEQUENTIAL_WRITE,
            ..Default::default()
        }, 
        vec![vert1, vert2, vert3, vert4])
        .unwrap();
}
